name: Docker build

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - docker-compose.yml
      - .dockerignore
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker compose build
